name: My First Workflow

on: push

jobs:
    first_job: 
        runs-on: ubuntu-latest

        steps:
         - name: Welcome message
           run: echo "Welcome to ubuntu"

         - name: List files
           run: ls 

         - name: Read files
           run: cat README.md