name: My ShellScript Workflow

on: push

jobs:
    script_job: 
        runs-on: ubuntu-latest
        
        steps:
         - name: Checkout Repo
           uses: actions/checkout@v4

         - name: Shell script to displau welcome message and read file
           run: | 
            ./display.sh 